#! /bin/sh

# Prepare a freshly checked out copy of
# the git tree for compilation.

AMFLAGS=

GNULIB_MODULES="fpieee sockets calloc chown close ctype dirent errno error
                fclose fcntl-h fdl fflush fnmatch fnmatch-gnu fopen fprintf-posix
                fseek fsusage ftell getcwd getopt-gnu gpl-3.0 human idcache inttypes
                ioctl link locale lseek malloc mbrtowc mbsinit mbsstr
                mkdir mkstemp nanosleep printf-posix putenv readlink realloc
                rename rmdir signal sleep sprintf-posix stat stddef stdint
                stdio stdlib strcase strcasestr string strings strtoumax
                sys_stat sys_time sys_wait time uname unistd unlink
                wchar wcsnrtombs wctype write xalloc"

if [ "$1" = "-a" ]
then
    ../../gnulib/gnulib/gnulib-tool --import $GNULIB_MODULES ; echo -n .
#    gnulib-tool --update; echo -n .
#    patch -p0 < lib-Makefile.am.patch ; echo -n .
    AMFLAGS="--add-missing --force-missing --copy"
fi

cp .gitignore .gitignore.gnulib-backup
rm -rf autom4te.cache config.cache; echo -n "."
#libtoolize --automake --copy --force && echo -n "."
autoheader && echo -n "."
aclocal -I m4 && echo -n "."
automake --foreign $AMFLAGS && echo -n "."
autoconf && echo -n "."
rm -rf autom4te.cache config.cache `find lib m4 doc -name .gitignore` ; echo -n "."
mv .gitignore.gnulib-backup .gitignore
echo " done"
