.\" +----------
.\" |
.\" |			       git.transition man page
.\" |
.\" |	       Copyright 1993-2005 Free Software Foundation, Inc.
.\" |
.\" |	This file is part of GIT (GNU Interactive Tools)
.\" |
.\" |	GIT is free software; you can redistribute it and/or modify it under
.\" | the terms of the GNU General Public License as published by the Free
.\" | Software Foundation; either version 2, or (at your option) any later
.\" | version.
.\" |
.\" | GIT is distributed in the hope that it will be useful, but WITHOUT ANY
.\" | WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" | FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\" | details.
.\" |
.\" | You should have received a copy of the GNU General Public License along
.\" | with GIT; see the file COPYING. If not, write to the Free Software
.\" | Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\" |
.\" | $Id: git.transition.1,v 1.1 2005-10-22 15:29:15 ianb Exp $
.TH git.transition 1
.SH NAME
git.transition \- GNU Interactive Tools \- git transition script
.SH SYNTAX
.I git [arguments to gitfm]

.SH DESCRIPTION

The filemanager with GNU Interactive Tools (git) is now called
.I gitfm

git.transition is a very small script that replaces /usr/bin/git.
The script warns the user of the rename, and then runs gitfm(1),
passing any supplied arguments.

git was renamed to gitfm to avoid confusion with Linus Torvalds'
content tracker, also called git.

If you wish to complete the transition early, install git-core
and (as root) use:

 update-alternatives \-\-config git

.SH SEE ALSO
gitfm(1)

git(7) (part of the git-core package)

.SH AUTHORS
.I Tudor Hulubei <tudor@cs.unh.edu>
.br
.I Andrei Pitis <pink@pub.ro>
.br
.I Ian Beckwith <ianb@nessie.mcc.ac.uk> (Current maintainer)
