#! /bin/sh

###############################################################################
###									    ###
###		 GNU Interactive Tools per file type action script	    ###
###				   Global version			    ###
###     Copyright (C) 1994-2000, 2006-2007 Free Software Foundation, Inc.   ###
###                                                                         ###
###                  This file is part of gnuit.                            ###
###                                                                         ###
###  gnuit is free software: you can redistribute it and/or modify it       ###
###  under the terms of the GNU General Public License as published         ###
###  by the Free Software Foundation, either version 3 of the               ###
###  License, or (at your option) any later version.                        ###
###                                                                         ###
###  gnuit is distributed in the hope that it will be useful, but           ###
###  WITHOUT ANY WARRANTY; without even the implied warranty of             ###
###  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          ###
###  GNU General Public License for more details.                           ###
###                                                                         ###
###  You should have received a copy of the GNU General Public              ###
###  License along with this program. If not, see                           ###
###  http://www.gnu.org/licenses/.                                          ###
###									    ###
###		    Written by Tudor Hulubei and Andrei Pitis.		    ###
###			  Enhanced by Verdoolaege Sven.		            ###
###									    ###
###############################################################################

###
### This script executes a different action for each file type
### specified.  It tries to match the second parameter against the
### patterns specified in the 'case' statement (see below).
###
### If you want to add new file types & actions to this script, just
### add a new entry to the 'case' statement *before* the last one
### ( *) ... )
###
### For greater flexibility, gitaction's first parameter is the name
### of the directory where the file resides.  The complete file name
### is obtained by appending the file base name to the file path:
### "$1/$2".
###
### If you enhance this script, please send me a patch at
### gnuit-dev@gnu.org.  I'll include it in the next release.
###

###
### Instead of hardcoding `more' or `less' here, we can use GIT_PAGER,
### a shell environment variable that is bound on one of them, depending
### on your environment.  The default is to call `more', but you can
### change GIT_PAGER to point to your favorite pager...
###

###
### Thanks to John Stump for suggesting me to get rid of gitmatch.
### Thanks to Juhapekka Tolvanen <juhtolv@silmu.st.jyu.fi> for the new
### mikmod-related entries.
###

###
### Note:
### Not all the programs called here are able to handle the -- command
### line switch.  These are: emacs, ghostview, tar, basename, ar, xv,
### xanim, xfig, lynx, mpeg_vga, zip/unzip.  There are some that I couldn't
### test.
###
### When these programs will be fixed, we should add -- to them...
### Until then, we will fail to run commands like `xfig -P -P' to
### process a file called `-P'.
###

name=`basename "$0"`
msg="Press ENTER to continue..."
GIT_PAGER=${GIT_PAGER:-more}

#################### helper functions ####################

cleanup()
{
    if test -n "$tempfile" && test -f "$tempfile"; then
	rm -f "$tempfile"
    fi
}

doexit()
{
    ret=$1
    echo "$msg"; read key;
    cleanup
    exit $ret
}

exitifdone()
{
    if test $? -eq 0; then
	doexit
    fi
}

whichlist()
{
    while test $# -gt 0
    do
	gitwhich "$1"
	if test $? -ne 0; then
	    return 1
	fi
	shift
    done
    return 0
}

TRY_NORMAL=0
TRY_PAGED=1
TRY_X=2

dotry()
{
    type=$1
    cmd="$2"
    shift
    shift
    if whichlist "$cmd"; then
	case $type in
	    $TRY_NORMAL)	"$cmd" "$@" ;;
	    $TRY_PAGED)		"$cmd" "$@"  2>&1 | "$GIT_PAGER" ;;
	    $TRY_X)		("$cmd" "$@"  >/dev/null 2>&1 ; cleanup ) & 
	    			tempfile=  ;; # don't delete tempfile now
	    *) 			 echo "$name: INTERNAL ERROR: unknown type ($type)" ;;
	esac
    fi
    doexit
}

try()
{
    dotry $TRY_NORMAL "$@"
}

trypaged()
{
    dotry $TRY_PAGED "$@"
}

tryx()
{
    if test -n "$DISPLAY"; then
	dotry $TRY_X "$@"
    fi
}

totempfile()
{
    tmpfile="${TMPDIR:-/tmp}/gitaction.$$"
    if whichlist "$1"; then
	"$@" > "$tmpfile"
	if test $? -eq 0; then
	    echo "$tmpfile"
	else
	    rm -f  "$tmpfile"
	fi
    fi
}

tryvideo()
{
    for prog in gmplayer xine totem mplayer xanim aktion;
    do 
	tryx "$prog" "$file"
    done
    try mplayer -vo svga "$file"
}

tryaudio()
{
    tryx audacious     "$file"
    tryx xmms          "$file"
    tryx amp           "$file"
    tryx x11amp        "$file"
    try  amp           "$file"
}

#################### Main logic ####################

if test "$#" -ne 2; then
    echo "$name: GIT internal script" >&2
    doexit 1
fi

if test ! -d "$1"; then
    echo "$name: $1 is not a directory"
    doexit 1
fi

if test ! -f "$1/$2"; then
    echo "$name: file $1/$2 does not exist"
    doexit 1
fi

if test -f .gitaction; then
    ./.gitaction "$1" "$2"
    exitifdone
fi

if test -f $HOME/.gitaction; then
    $HOME/.gitaction "$1" "$2"
    exitifdone
fi

file="$1/$2"

istext=0
if whichlist file; then
    file "$file" |grep -q '.*:.*text'
    istext=$?
fi

lcfile="$(echo "$file"|tr [:upper:] [:lower:])"

# Handle listing compressed archives first, to avoid decompressing
# them to disk just to list them

case "$lcfile" in
    *.tar.gz|*.pkg|*.t[arg]z) if whichlist gunzip tar; then
				  gunzip  -c "$file" | tar tvf -    | "$GIT_PAGER"
				  doexit
			      fi ;;
    *.tar.bz2|*.tbz)          if whichlist bunzip2 tar; then
				  bunzip2 -c "$file" | tar tvf -    | "$GIT_PAGER"
				  doexit
			      fi ;;
    *.cpio.gz)                if whichlist gunzip cpio; then
				  gunzip  -c "$file" | cpio -t 2>&1 | "$GIT_PAGER"
				  doexit
			      fi ;;
    *.cpio.bz2)               if whichlist gunzip cpio; then
				  bunzip2 -c "$file" | cpio -t 2>&1 | "$GIT_PAGER"
				  doexit
			      fi ;;
esac

lcbase="$(echo $lcfile |sed -e 's/\(.*\)\..*/\1/')"

tempfile=""
case "$lcfile" in
    *.gz)  	tempfile="$(totempfile gunzip -c                "$file")" ;;
    *.bz)  	tempfile="$(totempfile bunzip -c                "$file")" ;;
    *.bz2) 	tempfile="$(totempfile bzcat                    "$file")" ;;
    *.z)   	tempfile="$(totempfile uncompress -c            "$file")" ;;
    *.uu|*.uue)	tempfile="$(totempfile uudecode -o /dev/stdout  "$file")" ;;
esac

if test -n "$tempfile"; then
    file="$tempfile"
    lcfile="$lcbase"
fi

# MacOS only
if test `uname -s` = "Darwin"; then
    # don't run open(1) on text files
    if test $istext -eq 0 ; then
	try open "$file"
    fi;
fi

case "$lcfile" in
*.so | *.so.[0-9]* |\
*.o | *.lo)	trypaged objdump --syms --all-headers -- "$file" ;;

*.a|*.sa)	trypaged ar -tv       "$file" ;;
*.tar|*.cbt)	trypaged tar tvf      "$file" ;;
*.cpio)		trypaged cpio -t -F   "$file" ;;

*.html|*.htm)	if test "$GIT_BROWSER"; then
		    try "$GIT_BROWSER" "$file"
		fi
		try lynx   "$file"
		try w3m    "$file"
		try elinks "$file"  ;;

*.chm)		tryx gnochm      "$file"
		tryx kchmviewer  "$file"
		tryx chmsee      "$file"
		tryx xchm        "$file" ;;

*.sqlite)	trypaged sqlite  "$file" .dump ;; 
*.db)		trypaged db_dump "$file" ;;
*.dbf)		trypaged dbview  "$file" ;;
*.dia)		tryx     dia     "$file" ;;
*.dot)		tryx     dotty   "$file" ;;

*.djvu)		tryx djview4     "$file"
		tryx djview3     "$file"
		tryx djview      "$file" ;;

utmp)		trypaged w ;;

wtmp | wtmp.[0-9]*)
		trypaged last -f "$file" ;;

*ring.pgp)	trypaged pgp -kv --  "$file" ;;
*pgp)		try      pgp --      "$file" ;;
*gpg)		try      gpgv --     "$file" ;;
*.fig)		tryx     xfig        "$file" ;;

*.123 | *.602 | *.dbf | *.doc |\
*.wri | *.ot  | *.mml | *.ppt |\
*.rtf | *.wb2 | *.wp  | *.wps |\
*.xls |*.xl[sct]  | *.wp[5ds] | *.doc[mx] |\
*.dot[mx] | *.od[bcfgmpst] | *.ot[ghpst] |\
*.pot[mx] | *.pps[mx]  | *.ppt[mx] |\
*.sd[abcdfsw] | *.sg[lk] | *.st[cdiw] |\
*.sx[cdgimw] | *.xls[mx] |\
*.xlt[mx])	tryx openoffice    "$file"
		tryx soffice       "$file"
		tryx AbiWord       "$file" ;;

*.gnumeric)	tryx gnumeric      "$file" ;;
*.oleo)		try oleo           "$file" ;;

*.afm | *.bdf | *.cff | *.cid |\
*.mmm | *.ocf | *.ofm | *.otf |\
*.pcf | *.pfa | *.pfb | *.pfm |\
*.ttf | *.font)	tryx gfontview     "$file" ;;
		tryx gwaterfall    "$file" ;;


*.gif | *.jpg | *.jpeg |\
*.tga | *.bmp | *.ppm |\
*.pnm | *.pgm | *.pbm |\
*.tif | *.tiff | *.bm |\
*.xbm | *.xpm | *.ras |\
*.rgb | *.png | *.fts |\
*.pam | *.ico)	tryx xzgv          "$file"
		tryx kview         "$file"
		tryx ee            "$file"
		tryx display       "$file"
		tryx xli           "$file"
		tryx xloadimage    "$file"
		tryx feh           "$file"
		tryx gqview        "$file"
		tryx feh           "$file"
		tryx gimp          "$file"
		tryx xv            "$file"
		try  zgv           "$file"
		try  fbi           "$file" ;;

*.xcf | *.fit)	tryx gimp          "$file" ;;

*.mp[23])	tryaudio           "$file"
		try  mpg123 -v     "$file"
		try  mpg321 -v     "$file" ;;

*.ogg)		tryaudio           "$file"
		try  ogg123 -v     "$file" ;;

*.flac)		tryaudio           "$file"
		try  flac123       "$file" ;;

*.wma | *.gsm)	tryaudio           "$file" ;;

*.asx | *.m3u |\
*.pls)		tryaudio              "$file"
		try mplayer -playlist "$file" ;;

*.asf | *.wm[vf] |\
*.mov | *.avi)	tryvideo           "$file" ;;

*.mp[4g]|*.mpeg) tryvideo          "$file" 
		 try mpeg_vga      "$file" ;;

*.fl[icv])	tryvideo           "$file" 
		try flip           "$file" ;;

*.swf)		tryx swfdec-player "$file"
		tryx firefox       "$file"
		tryx iceweasel     "$file" ;;

*.svg)		tryx gthumb        "$file"
		tryx ksvg          "$file"
		tryx display       "$file"
		tryx firefox       "$file"
		tryx iceweasel     "$file"
		tryx sodipodi      "$file"
		tryx gimp          "$file" ;;
*.gl)		tryx xgrasp        "$file" ;;

*.mod | *.mod.lha | *.mod.lzh | *.mod.zip |\
*.669 | *.669.lha | *.669.lzh | *.669.zip |\
*.dsm | *.dsm.lha | *.dsm.lzh | *.dsm.zip |\
*.far | *.far.lha | *.far.lzh | *.far.zip |\
*.med | *.med.lha | *.med.lzh | *.med.zip |\
*.mtm | *.mtm.lha | *.mtm.lzh | *.mtm.zip |\
*.ult | *.ult.lha | *.ult.lzh | *.ult.zip |\
*.it | *.it.lha | *.it.lzh | *.it.zip |\
*.xm | *.xm.lha | *.xm.lzh | *.xm.zip |\
*.s[3t]m | *.s[3t]m.lha| *.s[3t]m.lzh| *.s[3t]m.zip)
		(mikmod -t "$file" > /dev/null 2>&1 &);;

*.r[av]|*.ram)	for prog in realplay rvplayer raplayer
		do
		    tryx "$prog" "$file"
		done
		tryvideo "$file" ;;

*.voc)		(vplay "$file" > /dev/null 2>&1 &);;

*.wav)		for prog in audacious xmms kmedia wavplay
		do
		    tryx "$prog" "$file"
		done
		try wavplay "$file"
		try play    "$file" ;;

*.aiff|*.aifc)	tryx audacious       "$file"
		tryx alsaplayer-gtk  "$file"
		try  alsaplayer-text "$file"
		tryx alsaplayer      "$file"
		try  alsaplayer      "$file"  ;;

*.rmd)		if whichlist rmdtopvf pvftobasic; then
		    (rmdtopvf -8 "$file" 2> /dev/null |
		     pvftobasic > /dev/audio 2> /dev/null &)
		     doexit
		fi;;

*.pvf)		if whichlist pvftobasic; then
		    (pvftobasic > /dev/audio 2> /dev/null &)
		    doexit
		fi;;
*.au)		(cat "$file" > /dev/audio 2> /dev/null &); doexit ;;

*.midi |*.mid)	if whichlist playmidi; then
		    (playmidi $PLAYMIDIOPT "$file" > /dev/null 2>&1 &)
		    doexit
		fi;;

*.sf2 | *.sfx | *.sbk)
		tryx swami         "$file" ;;

*.torrent)	try btshowmetainfo "$file" ;;

*.ps | *.eps)	tryx evince        "$file"
		tryx gv            "$file"
		tryx kghostview    "$file"
		tryx ggv           "$file"
		tryx ghostview     "$file"
		try  fbgs          "$file"
		try  gs            "$file" ;;

*.dvi)		tryx kdvi          "$file"
		tryx xdvi          "$file" ;;

*.lyx)		tryx klyx          "$file"
		tryx lyx           "$file" ;;

*.pdf)		tryx evince        "$file"
		tryx acroread      "$file"
		tryx xpdf          "$file" ;;

*.pod)		trypaged pod2text  "$file" ;;
*.ms)		trypaged nroff -ms "$file" ;;

*.[1-9n] | *.[1-9n][xm] | *.[1357]ssl | *.[137]posix |\
*.[1-9]fun | *.[1-9n]freebsd | *.1emacs[0-9][0-9] |\
*.1[aelmpqx] | *.3[ow] | *.5[ag] | *.8[aclp] |\
*.[78]cdebconf | *.[158]cn | *.[35]el | *.[135]gv |\
*.[135]nas | *.[13]pvm | *.[35]snmp | *.[1357]wn | \
*.[37]tcl | *.[1-9]x | *.1gmt | *.1grass | *.1olvwm | \
*.1sr | *.1viewos | *.3abz | *.3alleg | *.3aolserver |\
*.3ber | *.3blt | *.3bobcat | *.3caca | *.3curses |\
*.3debug | *.3diet | *.3el | *.3erl | *.3f90 |\
*.3form | *.3gdbm | *.3gle | *.3itcl | *.3itk |\
*.3iv | *.3iwidget | *.3iwidgets | *.3kaya |\
*.3m17n | *.3menu | *.3ncp | *.3ncurses | *.3ossp |\
*.3perl | *.3plplot | *.3pm | *.3pub | *.3qt |\
*.3readline | *.3ruby | *.3tclx | *.3tiff | *.3tix |\
*.3tk | *.3trf | *.3xp | *.5el | *.5heimdal | *.7cdebconf |\
*.7g | *.7wn | *.8cdebconf | *.8mailutils | *.8postfix |\
*.8tp | *.man)	trypaged nroff -man "$file" ;;

*.[iI]nfo)	try info --file "$file";;

[SR]MAIL)	try emacs   "$file"
		try xemacs  "$file" ;;

INBOX|OUTBOX)	try xemacs  "$file" ;;


*.arj |\
*.a[0-9][1-9])	trypaged unarj l   "$file" ;;
*.zip|*.cbz)	trypaged unzip -v  "$file" ;;
*.rar|*.cbr)	trypaged unrar l   "$file" ;;
*.zoo)		trypaged zoo -list "$file" ;;
*.jar)		trypaged jar tvf   "$file" ;;
*.lha|*.lzh)	trypaged lha -v    "$file" ;;
*.class)	trypaged javap -c -s -l -verbose "$(basename "$file" .class)" ;;
*.rpm)		trypaged rpm -qilRsp -- "$file" ;;

*.deb)		if whichlist dpkg; then
		    (echo "$file"; dpkg --info "$file";
		     echo; dpkg --contents "$file") | "$GIT_PAGER"
		    doexit
		fi
esac

if test -x "$file"; then
    if test `uname` = "Linux"; then
	FILE_OPTIONS="-L"
    fi
    file $FILE_OPTIONS "$file" | grep "ELF" > /dev/null 2>&1
    if test $? -eq 0; then
	file $FILE_OPTIONS "$file"
	ldd "$file"
	doexit
    fi
fi
FILEOUT="$(file --mime-type "$file" 2>/dev/null)"
if test $? -eq 0; then
    MIMETYPE="$(echo "$FILEOUT" | sed 's/.*: *//;')
fi
if test -n "$MIMETYPE" && test $istext -ne 1; then
    try see "${MIMETYPE}:${file}"
    try metamail -d -b -c "$MIMETYPE" "$file"
fi
try "$GIT_PAGER" "$file"
try less         "$file"
try more         "$file"
try cat          "$file"

cleanup
exit 1
