#! /bin/sh

###############################################################################
###									    ###
###		   GNU Interactive Tools recursive grep script		    ###
###	 Copyright (C) 1994-2000, 2006-2007 Free Software Foundation, Inc   ###
###		    Written by Tudor Hulubei and Andrei Pitis.              ###
###									    ###
###############################################################################

### $Id: gitrgrep,v 1.1.1.1 2004-11-10 17:44:38 ianb Exp $

grep="grep"
name=`basename "$0"`

# Start grep/egrep/fgrep depending on argv[0]

case $name in
gitrgrep)	grep="grep";;
gitregrep)	grep="egrep";;
gitrfgrep)	grep="fgrep";;
esac

find . -follow -type d -exec gitxgrep '{}'\
	$grep "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" ';'
