#! /bin/sh

###############################################################################
###									    ###
###		   GNU Interactive Tools recursive grep script		    ###
###	      Copyright (C) 1994-1999 Free Software Foundation, Inc.        ###
###		    Written by Tudor Hulubei and Andrei Pitis.              ###
###									    ###
###############################################################################

### $Id: gitrgrep,v 1.6 1999/01/16 22:37:23 tudor Exp $

grep="grep"
name=`basename "$0"`

# Start grep/egrep/fgrep depending on argv[0]

case $name in
gitrgrep)	grep="grep";;
gitregrep)	grep="egrep";;
gitrfgrep)	grep="fgrep";;
esac

find . -follow -type d -exec gitxgrep '{}'\
	$grep "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" ';'
